export const PLAN_LIMITS = {
  free: {
    agents: 1,
    messagesPerMonth: 50,
    contacts: 25,
    channels: ['web'] as const,
    knowledgeFiles: 1,
    customFunctions: 0,
    mcpServers: 0,
    subAccounts: 0,
    humanTakeover: false,
    voiceMessages: false,
    imageVision: false,
    allowedModels: ['gpt-4o-mini'],
    contextWindowMessages: 10,
    maxTokensPerResponse: 512,
    byoApiKey: false,
    emailNotificationTools: 0,
  },
  starter: {
    agents: 3,
    messagesPerMonth: 1000,
    contacts: 500,
    channels: ['web', 'whatsapp'] as const,
    knowledgeFiles: 5,
    customFunctions: 2,
    mcpServers: 0,
    subAccounts: 0,
    humanTakeover: true,
    voiceMessages: true,
    imageVision: false,
    allowedModels: ['gpt-4o-mini', 'claude-haiku-4-5-20251001'],
    contextWindowMessages: 15,
    maxTokensPerResponse: 1024,
    byoApiKey: false,
    emailNotificationTools: 2,
  },
  pro: {
    agents: 10,
    messagesPerMonth: 5000,
    contacts: 2000,
    channels: ['web', 'whatsapp'] as const,
    knowledgeFiles: 20,
    customFunctions: 10,
    mcpServers: 3,
    subAccounts: 5,
    humanTakeover: true,
    voiceMessages: true,
    imageVision: true,
    allowedModels: ['gpt-4o-mini', 'gpt-4o', 'claude-haiku-4-5-20251001', 'claude-sonnet-4-20250514'],
    contextWindowMessages: 25,
    maxTokensPerResponse: 2048,
    byoApiKey: false,
    emailNotificationTools: 10,
  },
  enterprise: {
    agents: Infinity,
    messagesPerMonth: 25000,
    contacts: Infinity,
    channels: ['web', 'whatsapp'] as const,
    knowledgeFiles: Infinity,
    customFunctions: Infinity,
    mcpServers: Infinity,
    subAccounts: Infinity,
    humanTakeover: true,
    voiceMessages: true,
    imageVision: true,
    allowedModels: ['gpt-4o-mini', 'gpt-4o', 'claude-haiku-4-5-20251001', 'claude-sonnet-4-20250514'],
    contextWindowMessages: 50,
    maxTokensPerResponse: 4096,
    byoApiKey: true,
    emailNotificationTools: Infinity,
  },
} as const;

export const PRICING = {
  starter: {
    monthly: 29,
    quarterly: 78.30,   // 10% off
    yearly: 278.40,     // 20% off
    quarterlyDiscount: 0.10,
    yearlyDiscount: 0.20,
  },
  pro: {
    monthly: 79,
    quarterly: 213.30,
    yearly: 758.40,
    quarterlyDiscount: 0.10,
    yearlyDiscount: 0.20,
  },
  enterprise: {
    monthly: 199,
    quarterly: 537.30,
    yearly: 1910.40,
    quarterlyDiscount: 0.10,
    yearlyDiscount: 0.20,
  },
} as const;

export const MESSAGE_ADDONS = [
  { messages: 500, price: 10 },
  { messages: 2000, price: 30 },
  { messages: 5000, price: 60 },
] as const;
